/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EADCOLONY_AUTODEFS_H
#define S3EADCOLONY_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ADCOLONY_NAME "s3eAdColony"
#define S3E_EXT_ADCOLONY_HASH 0x1cf88da9

#endif /* !S3EADCOLONY_AUTODEFS_H */
